### PR TITLE
Update MIT license

### PR DESCRIPTION
**Pull request by vinkla**
Added 2015 and email address.

### CODE REVIEW

**Comment by ivanakimov** [comment]
Why change the License paragraph in README? :]

**Comment by vinkla** [comment]
It's just different paragraph length.

**Comment by GrahamCampbell** [comment]
> but you kinda got rid of the rest of the sentence.

The short sentence with a link is a more standard way of linking to the license.

**Comment by ivanakimov** [comment]
Yeah, I get the link part. I'm talking about removing my goofy "Don't break the Internet. Kthxbye."

**Pull request merged**
