### PR TITLE
Simplify ignore file

### PR DESCRIPTION
**Pull request by vinkla**
Just removed unnecessary ignored files.

### CODE REVIEW

**Comment by ivanakimov** [comment]
I haven't seen .DS_Store ignored on my system, that's why I added it initially. tmproj is my TextMate project file.

**Comment by vinkla** [comment]
I'd argue that should be in the system ignore as well. Like myself, I use php storm a lot but I never add .idea folder to my packages.

**Comment by vinkla** [comment]
Any update on this?

**Comment by ivanakimov** [comment]
Sorry, been busy with startups lately! Yes, definitely will clean up the last few PRs and push a new version after testing. I want to pick a good time slot so I can do a few updates at once, so please bare with me as I catch up on my backlog.

Same for #46 of course.

**Comment by vinkla** [comment]
No worries, let me know if I can help out!

**Comment by vinkla** [comment]
:+1:

**Pull request merged**
