### PR TITLE
fix broken logo url in the readme page 

### PR DESCRIPTION
**Pull request by PhilETaylor**

### CODE REVIEW

**Comment by ivanakimov** [comment]
Thank you :+1: I'm a bit behind on my todo list...

**Comment by PhilETaylor** [comment]
Actually looking at it - all the hashids repos have this logo issue :-1:  - and from the google cache I think its meant to be the test "hashids" and not the green round avatar...

**Comment by ivanakimov** [comment]
Yep yep, the website used to be hosted on AWS S3, (not Github as it is now) and when I moved I forgot I had linked the logo to S3's now defunct bucket. Just gotta pick the right time, and update all. Thanks for the nudge, gets my butt moving faster... Will fix all sooner.

**Comment by PhilETaylor** [comment]
No worries - we all have todo lists longer than hours in the day :) just saw a quick win but on deeper scratching there appears to be a rabbit hole Im not getting sucked into - this time :) :)

**Comment by ivanakimov** [comment]
Haha, that's funny. Pushed it up on my rabbit hole todo list :]

**Pull request merged**
