### PR TITLE
Run Travis CI with GMP and BC

### PR DESCRIPTION
**Pull request by jkramarz**
Can't find cleaner option without using RunKit.

### CODE REVIEW

**Comment by vinkla** [comment]
Looks good! Just one question, is it common to use the `.travis` directory for tests?

**Comment by vinkla** [comment]
Would it be possible to add the config directly to the `.travis.yml` file?

**Comment by jkramarz** [comment]
I can't find a way to break line in `.travis.yml`, so it looks a bit scary, but does not require these configuration files.
https://github.com/jkramarz/hashids.php/blob/travis-test/.travis.yml
What do you think?

**Comment by vinkla** [comment]
@jkramarz I think it looks fine with long lines. As soon as you've updated I'll merge.

**Comment by jkramarz** [comment]
Done.

**Comment by vinkla** [comment]
Awesome, thank you @jkramarz!

**Pull request merged**
