### PR TITLE
Updated README.md to improve readability

### PR DESCRIPTION
**Pull request by ignaciogc**
Nothing major, but there were a few places where the documentation could be clarified / re-worded.

### CODE REVIEW

**Comment by ivanakimov** [comment]
Thank you @tiny-titan, I like the changes. Two points tho:
- I try to avoid using the term "hashed ids". These ids are not technically hashes, since they can be decoded back.
- If you have the energy, https://github.com/ivanakimov/hashids.js could use some help too (it's an almost identical `README.md` copy of this one)

**Comment by ivanakimov** [comment]
Yep, totally understand. There's a bit of history with using the word "hash" (we even thought about renaming the library at some point). If we could use the terms "id" or "string id" or "output id", I think it'd be better. Personally I prefer just "ids" for the simplicity, but I'm open to other suggestions. The rest of the changes look really good!

**Comment by ignaciogc** [comment]
I've updated the text to avoid using **hashed** ids, and instead using **output** ids.

**Comment by ivanakimov** [comment]
Thank you @ignaciogc :+1:

**Comment by ignaciogc** [comment]
No problem. I'll look at the Javascript version next and update with similar changes.

**Pull request merged**
